# Generated by Django 2.2 on 2019-04-11 16:49

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brand_logo/%Y/%m/%d')),
                ('status', models.BooleanField(default=False)),
                ('header_content', ckeditor.fields.RichTextField(help_text='\n    Content of the header (html), variables or\n    dynamic content {{myvar}} eg: {{name}}.\n', verbose_name='Header')),
                ('footer_content', ckeditor.fields.RichTextField(help_text='\n    Content of the header (html), variables or\n    dynamic content {{myvar}} eg: {{name}}.\n', verbose_name='Footer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brand',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Mailings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(help_text='ej. soport@mybrand.com', max_length=254, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_brand', to='mailings.Brand')),
            ],
            options={
                'verbose_name': 'mailing',
                'verbose_name_plural': 'mailings',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='name')),
                ('description', models.CharField(db_index=True, max_length=255, verbose_name='description')),
                ('subject', models.CharField(db_index=True, max_length=255, verbose_name='subject')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='\n    Content of the body (html), variables or\n    dynamic content {{myvar}} eg: {{name}}.\n', verbose_name='content')),
                ('mailing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mailings.Mailings')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='mailings.Brand')),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'ordering': ('name',),
            },
        ),
    ]
