# Generated by Django 2.2 on 2019-04-11 21:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='mailings',
            options={'ordering': ('id',), 'verbose_name': 'Mailing', 'verbose_name_plural': 'Mailings'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('name',), 'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to='brand_logo/%Y/%m/%d', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_brand', to='mailings.Brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='email',
            field=models.EmailField(help_text='eg. soport@mybrand.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Sender Name'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='template',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='mailings.Brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='template',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='\n    Content of the body (html), variables or\n    dynamic content {{myvar}} eg: {{name}}.\n', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mailing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mailings.Mailings', verbose_name='Mailing'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='template',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='template',
            name='subject',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
