# Generated by Django 2.2 on 2019-04-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'ordering': ('id',), 'verbose_name': 'mailing', 'verbose_name_plural': 'mailings'},
        ),
    ]
