# Generated by Django 2.2 on 2019-04-08 18:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='footer_content',
            field=ckeditor.fields.RichTextField(verbose_name='Footer'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='header_content',
            field=ckeditor.fields.RichTextField(verbose_name='Header'),
        ),
    ]
