# Generated by Django 2.2 on 2019-04-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='email_from',
            field=models.EmailField(default='', help_text='ej. soport@mybrand.com', max_length=254, verbose_name='email from'),
            preserve_default=False,
        ),
    ]
