# Generated by Django 2.2 on 2019-04-11 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_auto_20190411_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField(verbose_name='Request Params')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.Template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Postal System',
                'verbose_name_plural': 'Postal System',
                'ordering': ('id',),
            },
        ),
    ]
