# Generated by Django 2.2 on 2019-04-08 18:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_auto_20190408_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
