# Generated by Django 2.2 on 2019-04-11 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
