# Generated by Django 2.2 on 2019-04-08 19:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_auto_20190408_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='header_content',
            field=ckeditor.fields.RichTextField(help_text='This is a help text', verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
